# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "/img/favicon.ico"
    keywords: 探险者安全团队 开发 安全
    backgroundpic : "img/bg.jpg"

Intro:
    name: 探险者安全团队
    slogan: "Whatever is worth doing is worth doing well <br/>凡是值得做的事都值得做好 <br/> I'll think of you every step of the way <br/>我会每一步都想着你"
    HeadButton: 探险者安全团队

Nav:
    Home_name: 主页面
    is_use_categories : true 
    categories_name: 文章分类
    is_use_archives : true
    archives_name: 归档
    
    #Social
    # for more icons, please see http://fontawesome.io/icons/#brand
    icon:
        
        weixin: https://mp.weixin.qq.com/s?__biz=MzkwMzY2MTcwMw==&mid=2247484184&idx=1&sn=57bd70c53ac337874d556081d58299dc&chksm=c09392f0f7e41be688f28e33dba8f2ad7fa6cb465f78ad3e7e5a9c7143a0313ccb4e4815aa76&token=148826876&lang=zh_CN#rd
    
    pages:

        团队 :
            link: "/group/"
       
        关于我们:
            link: "/tag/"
        #自定义标签名
        #   link：“路径”

MainFirst:
    name: Brave explorers  
    description: 开拓者独辟蹊径，保守者因循守旧 <br/> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong> 会当凌绝顶 一览众山小 </strong> 
    pic_url: /images/me.jpg
    goto_ulr: "https://www.google.com/chrome/"

Gallery :
    title: 探险者安全团队 
    description: Just another fine responsive 

# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Custom code Render System 自定义代码渲染 
# default dark funky okaidia twilight coy solarized  可选项  
# link to review : http://prismjs.com/index.html   官网预览
prism: Okaidia

# Custom Fonts
fonts: Helvetica, "Hiragino Sans GB",FZLTCXHJW, "Helvetica Neue",  "Microsoft YaHei", "FZLTCXHJW", Arial, sans-serif

# Comment Systems
# Available value of "use":
#     duoshuo | disqus | disqus_click | changyan
comment:
    use: disqus_click
    shortname: http-miccall-tech 
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"
    changyan_appid:
    changyan_conf:
    changyan_thread_key_type: path
    # 使用 valine 请先执行 npm install valine --save
    valine: # Valine Comment System https://github.com/xCss/Valine
       on: true
       appId: 'your appId'
       appKey: 'your appkey'
       notify: true
       verify: false
       placeholder: Please leave your footprints
       avatar: ''
       avatar_cdn: https://gravatar.loli.net/avatar/ # avatar CDN address, default gravatar.loli.net
       pageSize: 10 # comments of one page

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: google
    swiftype_key: Just another fine responsive  
    

# Leancloud Views
leancloud:
    enable: false
    app_id: #你的 app_id
    app_key: #你的 app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: true
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"


# Mathjax 支持库 
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML